In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [3]:
## Define the vocabulary size
voc_size=10000
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3640, 8173, 4859, 7428],
 [3640, 8173, 4859, 7],
 [3640, 8852, 4859, 2037],
 [6665, 2783, 8341, 3958, 3546],
 [6665, 2783, 8341, 3958, 1757],
 [9121, 3640, 1699, 4859, 2357],
 [9557, 9268, 4736, 3958]]

In [5]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

In [7]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3640 8173 4859 7428]
 [   0    0    0    0 3640 8173 4859    7]
 [   0    0    0    0 3640 8852 4859 2037]
 [   0    0    0 6665 2783 8341 3958 3546]
 [   0    0    0 6665 2783 8341 3958 1757]
 [   0    0    0 9121 3640 1699 4859 2357]
 [   0    0    0    0 9557 9268 4736 3958]]


In [8]:
## feature representation
dim=10

In [9]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\KAVYA\ANN\venv_new\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 477ms/step


array([[[-0.04809065, -0.00946371,  0.02581655,  0.0114138 ,
          0.01896812, -0.04763696,  0.03908828, -0.04843929,
          0.02494712, -0.03056583],
        [-0.04809065, -0.00946371,  0.02581655,  0.0114138 ,
          0.01896812, -0.04763696,  0.03908828, -0.04843929,
          0.02494712, -0.03056583],
        [-0.04809065, -0.00946371,  0.02581655,  0.0114138 ,
          0.01896812, -0.04763696,  0.03908828, -0.04843929,
          0.02494712, -0.03056583],
        [-0.04809065, -0.00946371,  0.02581655,  0.0114138 ,
          0.01896812, -0.04763696,  0.03908828, -0.04843929,
          0.02494712, -0.03056583],
        [ 0.04413306, -0.02355387,  0.0286965 ,  0.01377895,
          0.02757442, -0.00076152, -0.04681214,  0.02836457,
          0.02145955, -0.04553617],
        [ 0.02324532,  0.0420859 ,  0.04269284,  0.0373669 ,
         -0.02165468,  0.02924594, -0.01674476,  0.0077072 ,
          0.02371622, -0.0211032 ],
        [-0.02527944, -0.02252014, -0.01552689,  0.0

In [12]:
embedded_docs[0]

array([   0,    0,    0,    0, 3640, 8173, 4859, 7428], dtype=int32)

In [13]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>